description: CCD User profile 
name: ccd-user-profile-api
apiVersion: v2
home: https://github.com/hmcts/ccd-user-profile-api
version: 1.4.2
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
dependencies:
  - name: java
    version: 2.17.0
    repository: '@hmctspublic'
