description: CCD User profile
name: ccd-user-profile-api
apiVersion: v2
home: https://github.com/hmcts/ccd-user-profile-api
version: 1.5.6
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
