java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    USER_PROFILE_DB_HOST: ccd-user-profile-api-postgres-db-v11-aat.postgres.database.azure.com
    USER_PROFILE_DB_NAME: ccd_user_profile
