java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
      secrets:
        - user-profile-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
  environment:
    DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
    DATA_STORE_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    DATA_STORE_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    DATA_STORE_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
    ENABLE_DB_MIGRATE: true
postgresql:
  enabled: true
